apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "testeeks3"
  annotations:
    github.com/project-slug: veecode-homolog/teste_env
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  
